# this file is used by the test suite to connect to the database
postgres:
  primary:
    database: pg_spec_helper
    username: specs_user
    password: specs_password
    host: localhost
    port: 5432
