# TypeProf 0.21.7

# Classes
class PGSpecHelper
  class MissingRequiredOptionError < StandardError
  end

  VERSION: String
  include TrackChanges
  include EmptyDatabase
  include Reset
  include MaterializedViews
  include Indexes
  include PrimaryKeys
  include UniqueConstraints
  include ForeignKeys
  include Validations
  include Columns
  include Tables
  include Schemas
  include IgnoredSchemas
  include Sanitize
  include Connection

  attr_reader database: String
  attr_reader username: String
  attr_reader password: nil | String
  attr_reader host: String
  attr_reader port: Integer
  def initialize: (database: String, host: String, port: Integer, username: String, ?password: String | nil) -> void

end
