# TypeProf 0.21.7

# Classes
class PGSpecHelper
  class MissingRequiredOptionError < StandardError
  end

  VERSION: String
  include Connection
  include IgnoredSchemas
  include Schemas
  include Tables
  include Columns
  include Validations
  include ForeignKeys
  include UniqueConstraints
  include PrimaryKeys
  include Indexes
  include Triggers
  include Functions
  include Extensions
  include Enums
  include Models
  include MaterializedViews
  include Reset
  include EmptyDatabase
  include TrackChanges

  attr_reader database: String
  attr_reader username: String
  attr_reader password: nil | String
  attr_reader host: String
  attr_reader port: Integer
  def initialize: (database: String, host: String, port: Integer, username: String, ?password: String | nil) -> void

end
