# TypeProf 0.21.7

# Classes
class PGSpecHelper
  module ForeignKeys
    def create_foreign_key: (Symbol schema_name, Symbol table_name, Symbol column_names, Symbol foreign_schema_name, Symbol foreign_table_name, Symbol foreign_column_names, Symbol foreign_key_name) -> void
    def get_foreign_key_names: (Symbol schema_name, Symbol table_name) -> Array[Symbol]
  end
end
