# TypeProf 0.21.7

# Classes
class PGSpecHelper
  module Schemas
    def create_schema: (:public schema_name) -> void
    def get_schema_names: -> Array[Symbol]
    def delete_all_schemas: (?cascade: false) -> void
    def schema_exists?: (Symbol schema_name) -> bool
  end
end
